### ISSUE TITLE
Crossterm 1.0 milestone ideas

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#249]
This issue describes the things required for the 1.0 release

List of tasks

- [x] Sync raw mode behavior across all platforms (#250)
- [x] Implement resize events (#165)
- [x] Have more unit tests 
- [x] Read sync should not return directly (#195)
- [x] Remove unsafe globals (#245)
- [x] Cursor position swallowed by input reader (#199)

**Comment by jonathandturner** [comment]
Congrats on working towards a 1.0 release.

Will #199 also be part of the 1.0 release?

**Comment by zrzka** [comment]
@jonathandturner it must be, it's a bug and the (async) reader, ... must be reimplemented. At least on UNIX. There're racing issues, etc.

**Comment by TimonPost** [comment]
Thanks! I will add that as well. There will be added more during the coming days. This is just the beginning :)

**Comment by TimonPost** [comment]
I had the idea to completely remove all or most of the structs:

```
TerminalCursor
TerminalInput
TerminalColor
Terminal
```

And only keep the [Command API](https://crossterm-rs.github.io/crossterm/docs/command.html#commands):

Motivations behind this:
- User has control over when to execute a command (flush ANSI-sequence to buffer) 
- Better Performance (because of manual flush)
- Complete control over where the ANSI escape commands are executed to
- Less maintenance
- Reducing the number of ways how you can use crossterm (`cursor().goto(), TerminalCursor::new().goto(), println!("{}", Goto()); io::stdout.execute(Goto()`); by focusing on one API we can create better code reduce the maintenance and duplicated documentation and will make it easier for the user.


Although, there are functionalities that are going to be difficult to move into the command API. Those problems are going to come up with all functions/methods that return a certain value. The commands are currently only supporting only set commands. I might have some idea on how we can transform that, but we should work something like that out in another issue. 

The following public interfaces are going to be removed. 

```rust
TerminalCursor and cursor()
TerminalInput and input()
TerminalColor and color()
Terminal and input()
```

Downsides: 
- Changing code is going to be more difficult, I've had many good experiences were I could just refactor the whole backend without touching the main structs that hided the implementations. 
- API might be more difficult for a user like: `println!("{}", Goto(5,5));` or `stdout.execute(Goto(5,5()` might seem weird for new users. Like `cursor().goto()` which is in my eyes easier to grasp what it

**Comment by TimonPost** [comment]
An other idea is to improve the input system. There are a couple of problems with how we do things currently, see #199. 

1. Allowed to have just one consumer. When not disposing the `Sync/Async Reader` and then create a new one will create two threads listening for input. Both trying to take an input before the other does.
2. When we get the cursor it can be swallowed by our reader (#199)
3. All the threading needs cleanup work and channels to work.
4. Read sync does not behave very well yet on windows, it returns directly instead of waiting for input. C# uses just a `while true` loop to have that functionality. We can do the same or make use of async in some way for this.

So what are the possible solutions? 

1. Make use of `std::future` async implementation. 
2. Create some kind of 1 producer -> multiple consumers type. 
3. Make sure there is one owner of the stding/tty, when we want to read cursor pos, it should somehow request access to the STDIN instead of just [using ](https://github.com/crossterm-rs/crossterm-cursor/blob/master/src/sys/unix.rs#L45)it. Which causes #199 

Possible solutions can be worked out in another issue, this issue is just about gathering ideas.

**Comment by TimonPost** [comment]
As discussed before, TerminalCursor, TerminalInput, TerminalColor, Terminal are stateless, and thus we might make those static. 

before: `TerminalCursor::new().goto(5,5)` to `TerminalCursor.goto(5,5)`

**Comment by TimonPost** [comment]
A list of functions not possible to use with the current commands:

```
Cursor::pos()
RawScreen::into_raw_mode()
RawScreen::disable_raw_mode()
Terminal::size()
```

We can either make them work with commands somehow or make those static functions. 


I think we are doing good by dropping all structs mentioned https://github.com/crossterm-rs/crossterm/issues/249#issuecomment-535023202, 

1. It is a deprecated API required by previous crossterm versions. 
2. Maintaining 2 API is a maintenance burden
3. The user has to think which API to use
4. It uses stdout by default
5. Boilerplate
