### ISSUE TITLE
Refactor the Style Module

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#286]
Related: #254 

# Task
Refactor the style module. 

# Todo
- [x] Remove `set_` prefix from `ObjectStyle` 
```rust
let style = ObjectStyle::new()
    .foreground(Color::Blue)
    .background(Color::Yellow)
    .attribute(Attribute::Italic);
    .attribute(Attribute::Bold);
    .attribute(Attribute::Crossed);
```

- [x] Rename `StyledObject` to `StyledContent`
- [x] Rename `ObjectStyle` to `ContentStyle`

Motivation behind this is that `StyledObject` wraps `Display` able content. And this is not really an 'Object'. So by renaming this to 'StyledContent'  it is more clear what it is, styled content. The same principle goes for `ObjectStyle` -> `ContentStyle`

- [x] Make `StyledContent` (StyledObject) fields private

```rust
pub struct StyledContent<D: Display + Clone> {
    object_style: ContentStyle,
    content: D,
}
```
Then add the following functions (if change 1,2 as well are approved. Otherwise replace `content_style` with `object_style`).

```rust 
fn content() -> D;
fn content_style() -> ObjectStyle
```
- [x] `Attribute::NoInverse` should be `Attribute::NoReverse`
- [x] Rename command `PrintStyledFont` to `PrintStyledContent`

- [x] `Crossterm::style()`
- [x] Remove re-exports from style module at at root and only expose those in the `crossterm::style` module.
- [x] Remove `TerminalColor` (/style.rs), 
- [x] Remove `color` (style.rs)
- [x] Move the winapi logic from `WinApiColor` into static functions in /style/sys/winapi  (sys is new folder) and use those in the commands. 
- [x] Remove `WinApiColor`, `AnsiColor` (/style/style),
- [x] Remove /style/style.rs
- [x] Update documentation
