### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#287]
This issue contains a list of things before 1.0 can be released.

- [X] Merging sub-crates into crossterm, issue: #280 
- [x] Remove everything except Command API, issue: #285
- [x] Refactor style module, issue: #286
- [x] Resize Events
   - #165
   - #284 
- [X] Refactor Input Module #288
   - PR #284
- [ ] Windows 7 Styled Object Fix
   - issue: #262 

.... in development

**Comment by TimonPost** [comment]
Closing this issue, because I would just like to solve the small bugs in the issue list first. When we don't have any work left, we can focus on plans for the roadmap. I think it is a bit too early.
