### ISSUE TITLE
Refactor Input Module

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#288]
Related: #249, #257 

# Task
Some refactoring to the input module. Renames, rewrites etc.

# Todo
- [X] MIO poll based implementation and allow multiple consumers
- [ ] Single consumer multiple producers 
    - #284
- [x] Allow masking for specific events when reading events. Like only `KeyEvent`
    - #284
- [x] Rename `enable_mouse_mode` -> `enable_mouse_events`
- [x] Rename `disable_mouse_mode` -> `disable_mouse_events`
- [x] Remove `read_until_async`
- [x] Rename `KeyEvent` to `Key`
- [ ] Rename `MouseEvent` to `Mouse`
- [x] Rename `InputEvent` to `Event`
- [x] Improve the way we are returning input events. 
      - 1. As a user, I want to see the occurred key event separate to the information whether Alt, Ctrl, Shift is pressed. Like: `InputEvent::KeyBord(KeyEvent::Char, KeyInfo)` where key info contains additional keypress info. 
- [ ] More tests for ANSI parsing

**Comment by doy** [comment]
has there been discussion about providing a futures/stream based async api? i'm having to do things like https://github.com/doy/teleterm/blob/master/src/key_reader.rs to be able to integrate the task notification stuff, and it'd really be nice if crossterm just provided that for me on its own.

**Comment by TimonPost** [comment]
We would like to support it when it is officially in rust. Thanks for the example. This PR should at least be ready to be used in a future stream. I think it does so via `EventPool::poll`, this block reads for input. So a future stream can be build around this function.

**Comment by zrzka** [comment]
@TimonPost he probably meant [`futures`](https://docs.rs/futures/0.1.29/futures/), especially this [`Stream`](https://docs.rs/futures/0.1.29/futures/stream/trait.Stream.html). Which will mean adding `tokio` as another dependency (`tokio` does use `mio`, not a big change). In my opinion, we should create an API without `futures` and also provide `features::Stream` way gated with the `features` feature for example.

**Comment by doy** [comment]
yup, that was my thought

**Comment by TimonPost** [comment]
Right, although I totally don't like to have tokio as dependency it is such a big library. Crossterm should be minimal and offer an interface that can be used in an async or non-async environment. Can't we work with STD lib futures when it is released? That's what I was waiting on instead of using tokio or futures...

**Comment by doy** [comment]
yeah - i have worked around it for now, so i'm not blocked on this or anything. that said, it's not super clear to me what the existing async api is useful for - although it is non-blocking, it doesn't provide any way that i can see to tell when data will be available, which means that the only way to use it is through a busy loop (and this is also what the examples in the docs show). this doesn't seem very useful to me - am i missing something about how it is supposed to be used?

**Comment by TimonPost** [comment]
Can be closed, the new input module is implemented by #284
